### ISSUE TITLE
Mindmap command is not showing in command palette 

### ISSUE THREAD

**Issue by Crakzzy** [james-tindal/obsidian-mindmap-nextgen#211]
![image](https://github.com/user-attachments/assets/4c006720-ad38-496c-8f85-f568a8fb8262)
![image](https://github.com/user-attachments/assets/306a235c-57a1-49f2-9edc-671641b4443b)
![image](https://github.com/user-attachments/assets/f6531e45-0afd-4197-b83e-23749880aa06)

**Comment by james-tindal** [comment]
I fixed this so it shouldn't have this conflict problem any more in the latest update.
